# This workflow builds the UI and commits the ui-bundle.zip file
# When the file is attached to a release, the documentation site can use it as its UI

name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: 20
    - name: Bundle UI
      run: |
        npm i
        gulp bundle
    - name: Commit files
      run: |
        git config --global user.name ${{ secrets.USER_NAME }}
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git add -f build
        git commit -m "Bundle UI"
        git push origin
