# This workflow:
# 1. builds the UI as build/ui-bundle.zip file
# 2. creates a new patch release
# 3. triggers production build

name: Publish

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: 22
    - name: Bundle UI
      run: |
        npm i
        npm run bundle
    - name: Commit files
      run: |
        git config --global user.name ${{ secrets.USER_NAME }}
        git config --global user.email ${{ secrets.USER_EMAIL }}
        git add -f build
        git commit -m "Bundle UI"
        git push origin
